[module]
  [module.hugoVersion]
    min = "0.114.0"
[menu]
  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"

[params]
user = "root"
hostname = "roudy.xyz"
  [params.author]
    name = "Roudy"  # Website and RSS feed author
    email = "NoEmail"

[[params.social]]
key = 1
name = "GitHub"
url = "https://github.com/Roxdyyy"

[[params.social]]
key = 2
name = "TikTok"
url = "https://tiktok.com/@roxdy"

[[params.social]]
key = 3
name = "Instagram"
url = "https://instagram.com/roxdyy"
