[module]
  [module.hugoVersion]
    min = "0.114.0"


[menu]
  [[menu.header]]
    name = "my code"
    weight = 0
    url = "code"
  [[menu.header]]
    name = "about"
    weight = 0
    url = "about"


[params]
user = "root"
hostname = "roudy.xyz"
  [params.author]
    name = "Roudy"  # Website and RSS feed author
    email = "placeholder@0legendary.xyz"

[[params.social]]
key = 1
name = "GitHub"
url = "https://github.com/Roxdyyy"

[[params.social]]
key = 4
name = "My MyMUN Profile"
url = "https://mymun.com/profile/294920"

[[params.social]]
key = 2
name = "TikTok"
url = "https://tiktok.com/@roudy.xyz"

[[params.social]]
key = 3
name = "Instagram"
url = "https://instagram.com/roxdyy"
